server:
  error:
    whitelabel:
      enabled: false

spring:
  datasource:
    url: jdbc:h2:mem:db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  redis:
    host: localhost
    port: 6379
